### ISSUE TITLE
Connection Abort on receiver side

### ISSUE THREAD

**Issue by ukbaranwal31** [trebleshot/android#151]
When i select files and then move on to Connection Options Screen to create an hotspot so receiver can connect with sender, sometimes the connection is happening, many times not. I am not able to understand the underlying issue for that, if you can help with that

1. Select Files
2. Setup hotspont
3. on receiver sides scan QR to get details
4. Connection aborted

**Expected behavior**
It was supposed to smoothly transfer files

**Log files**
> 2020-11-09 14:28:10.225 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
2020-11-09 14:28:10.227 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): No DHCP provided. Looping...
2020-11-09 14:28:11.233 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
2020-11-09 14:28:11.236 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): No DHCP provided. Looping...
2020-11-09 14:28:12.239 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
2020-11-09 14:28:12.239 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): No DHCP provided. Looping...
2020-11-09 14:28:13.243 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): Waiting to connect to the server
2020-11-09 14:28:13.247 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): DhcpInfo: gateway: 192.168.43.1 dns1: 192.168.43.1 dns2: 0.0.0.0 ipAddr: 192.168.43.146 serverAddr: 192.168.43.1 netMask: 0.0.0.0
2020-11-09 14:28:13.247 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): There is DHCP info provided waiting to reach the address 192.168.43.1
2020-11-09 14:28:13.305 28601-32409/com.example.trebleshot D/ConnectionUtils: establishHotspotConnection(): AP has been reached. Returning OK state.
2020-11-09 14:28:13.305 28601-32409/com.example.trebleshot D/Interrupt: HI192.168.43.11604912300
2020-11-09 14:28:14.787 28601-30041/com.example.trebleshot D/AccessPin: -1
2020-11-09 14:28:14.787 28601-30041/com.example.trebleshot D/Interrupt: HI192.168.43.1-1
2020-11-09 14:28:15.252 28601-30041/com.example.trebleshot D/connection: connection_interrupted
2020-11-09 14:28:15.252 28601-30041/com.example.trebleshot W/System.err: java.net.SocketException: Software caused connection abort
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:176)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:144)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:130)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.genonbeta.CoolSocket.CoolSocket$ActiveConnection.receive(CoolSocket.java:627)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.UIConnectionUtils$4.onConnect(UIConnectionUtils.java:221)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.CommunicationBridge.connect(CommunicationBridge.java:42)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.CommunicationBridge.connect(CommunicationBridge.java:30)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.UIConnectionUtils.setupConnection(UIConnectionUtils.java:209)
2020-11-09 14:28:15.253 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.UIConnectionUtils$3.onRun(UIConnectionUtils.java:140)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.util.InterruptAwareJob.run(InterruptAwareJob.java:11)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.service.WorkerService$RunningTask.run(WorkerService.java:362)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at com.example.share.service.WorkerService$1.run(WorkerService.java:188)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-11-09 14:28:15.254 28601-30041/com.example.trebleshot W/System.err:     at java.lang.Thread.run(Thread.java:919)
2020-11-09 14:28:15.309 28601-28601/com.example.trebleshot D/TestOverScroll: getScaledOverscrollDistance: b
2020-11-09 14:28:15.341 28601-28601/com.example.trebleshot D/ColorViewRootUtil: initSwipState, isDisplayCompatApp false

**Environment**
 - Android version: [Most of times the hotspot creator is Android 8.1 and receiver is 9]
 - App version [e.g. 1.2.7.6]
 - Device Model and Brand [e.g. Vivo 1820)]

**Comment by velitasali** [comment]
Because this is from a modified source code, I cannot provide help to this problem.
